--- 
:native_languages: 
  aa: Afar
  ab: "аҧсуа бызшәа"
  ae: Avestan
  af: Afrikaans
  ak: Akan
  am: "አማርኛ"
  an: Aragonese
  ar: "العربية"
  as: Assamese
  av: Avaric
  ay: Aymara
  az: "Azərbaycan"
  ba: Bashkir
  be: "Беларуская"
  bg: "Български"
  bi: Bislama
  bm: Bamanankan
  bn: Bengali
  bo: Tibetan
  br: Breton
  bs: Bosnian
  ca: "Català"
  ce: Chechen
  ch: Chamorro
  co: Corsican
  cr: Cree
  cs: "čeština"
  cu: Slavic
  cv: Chuvash
  cy: Cymraeg
  da: Dansk
  de: Deutsch
  dv: Divehi
  dz: Dzongkha
  ee: "Ɛʋɛ"
  eg: Engrish
  el: "Ελληνικά"
  en: English
  eo: Esperanto
  es: "Español"
  et: Eesti
  eu: Euskera
  fa: "فارسی"
  ff: Fulfulde, Pulaar, Pular
  fi: Suomi
  fj: Fijian
  fo: Faroese
  fr: "Français"
  fy: Frisian
  ga: Gaeilge
  gd: Gaelic
  gl: Galego
  gn: Guarani
  gu: Gujarati
  gv: Manx
  ha: Hausa
  he: "עברית"
  hi: "हिंदी"
  ho: Hiri Motu
  hr: Hrvatski
  ht: Haitian; Haitian Creole
  hu: Magyar
  hy: "Հայերեն"
  hz: Herero
  ia: Interlingua
  id: Bahasa indonesia
  ie: Interlingue
  ig: Igbo
  ii: Yi
  ik: Inupiaq
  io: Ido
  is: "Íslenska"
  it: Italiano
  iu: Inuktitut
  ja: "日本語"
  jv: Javanese
  ka: Georgian
  kg: Kongo
  ki: Kikuyu
  kj: Kuanyama
  kk: "Қазақ"
  kl: Kalaallisut
  km: Khmer
  kn: "ಕನ್ನಡ"
  ko: "한국어"
  kr: Kanuri
  ks: Kashmiri
  ku: Kurdish
  kv: Komi
  kw: Cornish
  ky: "Кыргыз"
  la: Latin
  lb: Letzeburgesch
  lg: Ganda
  li: Limburgish
  ln: Lingala
  lo: Lao
  lt: "Lietuviškai"
  lu: Luba-Katanga
  lv: "Latviešu"
  mg: Malagasy
  mh: Marshall
  mi: Maori
  mk: "Македонски"
  ml: Malayalam
  mn: Mongolian
  mo: Moldavian
  mr: Marathi
  ms: Bahasa melayu
  mt: Malti
  my: Burmese
  na: Nauru
  nb: "Norwegian Bokmål"
  nd: Ndebele
  ne: Nepali
  ng: Ndonga
  nl: Nederlands
  nn: Norwegian Nynorsk
  "no": Norsk
  nr: Ndebele
  nv: Navajo
  ny: Chichewa; Nyanja
  oc: Occitan
  oj: Ojibwa
  om: Oromo
  or: Oriya
  os: Ossetian; Ossetic
  pa: Panjabi
  pi: Pali
  pl: Polski
  ps: "پښتو"
  pt: "Português"
  qu: Quechua
  rm: Raeto-Romance
  rn: Kirundi
  ro: "Română"
  ru: "Pyccĸий"
  rw: Kinyarwanda
  sa: Sanskrit
  sc: Sardinian
  sd: Sindhi
  se: Northern Sami
  sg: Sango
  sh: Serbo-Croatian
  si: Sinhalese
  sk: "Slovenčina"
  sl: "Slovenščina"
  sm: Samoan
  sn: Shona
  so: Somali
  sq: Shqip
  sr: Srpski
  ss: Swati
  st: Sotho
  su: Sundanese
  sv: Svenska
  sw: Kiswahili
  ta: Tamil
  te: "తెలుగు"
  tg: Tajik
  th: "ภาษาไทย"
  ti: Tigrinya
  tk: Turkmen
  tl: Tagalog
  tn: Tswana
  to: Tonga
  tr: "Tϋrkçe"
  ts: Tsonga
  tt: Tatar
  tw: Twi
  ty: Tahitian
  ug: Uighur
  uk: "Українська"
  ur: "اردو"
  uz: O'zbek
  ve: Venda
  vi: "Tiếng Việt"
  vo: "Volapük"
  wa: Walloon
  wo: Wolof
  xh: Xhosa
  yi: Yiddish
  za: Zhuang
  zh: "中文"
  zu: isiZulu
